name: PGE323
dependencies:
- python=3.7
- pip:
  - appnope==0.1.0
  - blinker==1.4
  - cloudpickle==0.2.1
  - cycler==0.10.0
  - decorator==4.0.10
  - docutils==0.12
  - doit==0.29.0
  - entrypoints==0.2.2
  - husl==4.0.3
  - ipykernel==4.4.1
  - ipython==5.1.0
  - ipython-genutils==0.1.0
  - ipywidgets==5.2.2
  - jinja2==2.8
  - jsonschema==2.5.1
  - jupyter==1.0.0
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.1
  - logbook==1.0.0
  - lxml==3.6.4
  - mako==1.0.4
  - markdown==2.6.6
  - markupsafe==0.23
  - matplotlib==1.5.2
  - mistune==0.7.3
  - natsort==5.0.1
  - nbconvert==4.2.0
  - nbformat==4.1.0
  - nikola==7.7.12
  - notebook==4.2.2
  - numpy==1.11.1
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - piexif==1.0.5
  - pillow==3.3.1
  - prompt-toolkit==1.0.7
  - ptyprocess==0.5.1
  - pygments==2.1.3
  - pyparsing==2.1.8
  - pyrss2gen==1.1
  - python-dateutil==2.5.3
  - pytz==2016.6.1
  - pyzmq==15.4.0
  - qtconsole==4.2.1
  - requests==2.11.1
  - scipy==0.18.0
  - simplegeneric==0.8.1
  - six==1.10.0
  - terminado==0.6
  - tornado==4.4.1
  - traitlets==4.2.2
  - unidecode==0.4.19
  - wcwidth==0.1.7
  - widgetsnbextension==1.2.6
  - yapsy==1.11.223
